class Car{
	public static void main(String[] args){
		String password="keerthana123";
		System.out.println(password);
		String name="keerthana";
		System.out.println(name);
		String state="karnataka";
		System.out.println(state);
		String language="kannada";
		System.out.println(language);
		String hobby="drawing";
		System.out.println(hobby);
		String tourplace="japan";
		System.out.println(tourplace);
		String education="B.E";
		System.out.println(education);
		String typewriting="English";
		System.out.println(typewriting);
		String bestplace="udupi";
		System.out.println(bestplace);
		String nameofthebird="parrot";
		System.out.println(nameofthebird);
		String anyspicyfood="noodels";
		System.out.println(anyspicyfood);
		String sportsintersted="throwball";
		System.out.println(sportsintersted);
		String cultureplaces="southindia";
		System.out.println(cultureplaces);
		String streetsinbanglore="churchstreets";
		System.out.println(streetsinbanglore);
		String mallinbanglore="G T mall";
		System.out.println(mallinbanglore);
		String laptopis="software";
		System.out.println(laptopis);
		String mobileused="for app";
		System.out.println(mobileused);
		String bracheinengineering="computer science";
		System.out.println(bracheinengineering);
		String rulingpartyis="bjp";
		System.out.println( rulingpartyis);
		String university="vtu";
		System.out.println(university);
		String collegename="sdmit";
		System.out.println(collegename);
		String clothesused="for washing";
		System.out.println(clothesused);
		String medicine="ayruvedha";
		System.out.println(medicine);
		String ringusedinfingure="gold";
		System.out.println(ringusedinfingure);
		String raining="today";
		System.out.println(raining);
		String idli="breakfast";
		System.out.println(idli);
		String name1="siya";
		System.out.println("name1:"+name1);
	String age="21";
	System.out.println("age:"+age);
	String gmail="siyar123";
	System.out.println("gmail:"+gmail);
	String address="udupi";
	System.out.println("address:"+address);
	String country="India";
	System.out.println("country:"+country);
	String message="good morning";
	System.out.println("message:"+message);
	String degree="engineering";
	System.out.println("degree:"+degree);
	String presentLocation="bengaluru";
	System.out.println("presentLocation:"+presentLocation);
	String temperature="25.c";
	 System.out.println("temperature:"+temperature);
	String date="6/28/2024";
	System.out.println("date:"+date);
	String primeMinister="narendra modhi";
	System.out.println("primeMinister:"+primeMinister);
	String pincodeOfUdupi="576234";
	System.out.println("pincodeOfUdupi:"+pincodeOfUdupi);
	String favouriteColor="yellow";
	System.out.println("favouriteColor:"+favouriteColor);
	String dob="18/02/2003";
	System.out.println("dob:"+dob);
	String favouritePlace="America";
	 System.out.println("favouritePlace:"+favouritePlace);
	String favouriteFood="chicken";
	System.out.println("favouriteFood:"+favouriteFood);
	String height="4.10";
	System.out.println("height:"+height);
	String temperatur1="25.c";
	System.out.println("temperatur1:"+temperatur1);
	String primeMinister1="narendra modhi";
	System.out.println("primeMinister:"+primeMinister);
	String weight="40";
	System.out.println("weight:"+weight);
	String phoneNo="9972843127";
	System.out.println("phoneNo:"+phoneNo);
	String temperatureOfAtmosphere="25.c";
	System.out.println("temperatureOfAtmosphere:"+temperatureOfAtmosphere);
	String college="sdmit";
	System.out.println("college:"+college);
	String month="june";
	System.out.println("month:"+month);
	String state1="karnataka";
	System.out.println("state1:"+state1);
	String wheather="The wheather outside is ";
		System.out.println("wheather:"+wheather);
String people="outside there are so many people";
System.out.println("people:"+people);
String road="the road is busy of the people";
System.out.println("road:"+road);
String summer="this summer has very high temperature";
System.out.println("summer:"+summer);
String menu="there are lots of food in the menu";
System.out.println("menu:"+menu);
String chess="to play chess we required patience";
System.out.println("chess:"+chess);
String gold="gold is costly";
System.out.println("gold:"+gold);
String cricket="there are 11 players in the team";
System.out.println("cricket:"+cricket);
String rain="outside it is raining heavily";
System.out.println("rain:"+rain);
String electricity="there is no electricity ";
System.out.println("electricity:"+electricity);
String year="this year the temperature was very high";
System.out.println("year:"+year);
String language1="there are 13 languages are there";
System.out.println("language1:"+language1);
String exam="this time the exam was very tough";
System.out.println("exam:"+exam);
String country1="India is beautiful country";
System.out.println("country1:"+country1);
String continents="there are 7 continents are there";
System.out.println("continents:"+continents);
String dosa="dosa is very crispy";
System.out.println("dosa:"+dosa);
String spicy="Indian food is very spicy";
System.out.println("spicy:"+spicy);
String flower="there are different types of flower around there";
System.out.println("flower:"+flower);
String perfume="there are different scents of perfume";
System.out.println("perfume:"+perfume);
String sunday="sunday is holiday";
System.out.println("sunday:"+sunday);
String months="there are 12 months in the year";
System.out.println("months:"+months);
String falls="there are different waterfalls are there";
System.out.println("falls:"+falls);
String mountains="there are different mountains are there";
System.out.println("mountains:"+mountains);
String Biscuts="cream biscut is very tasty";
System.out.println("Biscuts:"+Biscuts);
String chats="there are different types of chats";
System.out.println("chats:"+chats);
	
        String combined="keerthana123"+"for gmail";
		System.out.println(combined);
		String combine="keerthana"+"for recognize";
		System.out.println(combine);
		String common="karnataka"+"keerthanalived";
		System.out.println(common);
		String correlate="kannada"+"to speak";
		System.out.println(correlate);
		String living="japan"+"to travel";
		System.out.println(living);
		String studing="B.E"+"to get job";
		System.out.println(studing);
		String writing="English"+"to write";
		System.out.println(writing);
		String enjoyingplaces="udupi"+"tovisit";
		System.out.println(enjoyingplaces);
		String bird="parrot"+"is beautiful";
		System.out.println(bird);
		String food="noodels"+"it is tasty";
		System.out.println(food);
		String sports="throwball"+"is hobby to play";
		System.out.println(sports);
		String culltural="southindia"+"is best place to visit in india";
		System.out.println(culltural);
		String streets="churchstreets"+"to do shopping";
		System.out.println(streets);
		String shopingmall="G T mall"+"provides best facilities";
		System.out.println(shopingmall);
		String working="software"+"in laptop is best to the working";
		System.out.println(working);
		String cont="for app"+"android is best mobile";
		System.out.println(cont);
		String streams="computer science"+"i have studied";
		System.out.println(streams);
		String rulling="bjp"+"have got higgest votes";
		System.out.println(rulling);
		String study="vtu"+"is a university";
		System.out.println(study);
		String college1="sdmit"+"where i have done education";
		System.out.println(college1);
		String purpose="for washing"+"the clothes in washingmachines";
		System.out.println(purpose);
		String tablets="ayruvedha"+"best to the health";
		System.out.println(tablets);
		String fashion="gold"+"is usually used for fingures";
		System.out.println(fashion);
		String weather="today"+"is raining";
		System.out.println(weather);
		String foodfor="breakfast"+"is idli today";
		System.out.println(foodfor);
        String june= "summer" + "cold";
        System.out.println(june);
		String fullName="siya"+"r";//concatenation
	System.out.println(fullName);
	String msg="good morning"+"have a good day";
	System.out.println(message);
	String quote="no BP"+"be happy";
	System.out.println(quote);
	String day="date"+"month";
	System.out.println(day);
	String word="temp"+"college";
	System.out.println(word);
	String body="height"+"weight";
	System.out.println(body);
	String education1="college"+"degree";
	System.out.println(education1);
	String favourite="favouriteColor"+"favouritePlace";
	System.out.println(favourite);
	String identity="name"+"age";
	System.out.println(identity);
	String location="address"+"presentLocation";
	System.out.println(location);
	/////////////
	String bodyy="body"+"weight";//concatenation
	System.out.println(bodyy);
	String msge="good morning"+"quote";
	System.out.println(msge);
	String quotee="no BP"+"be happy";
	System.out.println(quotee);
	String dayy="date"+"month";
	System.out.println(dayy);
	String loc="temp"+"college";
	System.out.println(loc);
	String primeMinisterr="narendra"+"modhi";
	System.out.println(primeMinisterr);
	String thing="washing"+"machine";
	System.out.println(thing);
	String company="x"+"workz";
	System.out.println(company);
	String person="body"+"knowledge";
	System.out.println(person);
	String dress="pant"+"top";
	System.out.println(dress);
	String parents="father"+"mother";
	System.out.println(parents);
	String thingg="air"+"conditioner";
	System.out.println(thingg);
	String companyy="x"+"workz";
	System.out.println(companyy);
	String personn="body"+"knowledge";
	System.out.println(personn);
	String dresss="saree"+"frock";
	System.out.println(dress);
	String june1= "summer" + "cold";
System.out.println(june1);
String fullName1= "neha" + "kiran G";
System.out.println(fullName1);
String subject= "social" + "science";
System.out.println(subject);
String brush= "tooth" + "paste";
System.out.println(brush);
String mood= "happy" + "sad";
System.out.println(mood);
String field= "play" + "ground";
System.out.println(field);
String hygine= "hand" + "wash";
System.out.println(hygine);
String birth= "happy" + "birthday";
System.out.println(birth);
String today= "the wheather" + "is very cold";
System.out.println(today);
String tommorrow= "tommorrow there will" + "be a rain";
System.out.println(tommorrow);
String sweet= "the candy is" + "very sweet";
System.out.println(sweet);
String food1= "the food is" + "very delcious";
System.out.println(food1);
String internet= "the internet" + "is very slow";
System.out.println(internet);
String traffic= "the road is" + "busy";
System.out.println(traffic);
String flowers= "there are" + "different types of flower";
System.out.println(flowers);
String nature= "the nature is" + "very beautiful";
System.out.println(nature);
String chilli= "red chilli" + "is very spicy";
System.out.println(chilli);
String color= "there are different" + "types of color";
System.out.println(color);
String bus= "there different types" + "of bus are there";
System.out.println(bus);
String rainbow= "there are 7" + "colors are there";
System.out.println(rainbow);
String stationary= "pen" + "penicil";
System.out.println(stationary);
String green= "the plants and trees" + "are green";
System.out.println(green);
String apple= "apple is red" + "in color";
System.out.println(apple);
String king= "mango is the" + "king of the fruits";
System.out.println(king);
		
	}
}